package com.example.sustclassnotifier.strings

const val SIGN_IN_BUTTON = "Log In"
const val SIGN_UP_BUTTON = "Sign Up"
const val FORGOT_PASSWORD_BUTTON = "Forgot Password"
const val RESET_PASSWORD_BUTTON = "Reset Password"
const val CREATE_CLASS_BUTTON = "Add Class"
const val SEARCH_COURSE_TEACHER_BUTTON = "Add Course Teacher"
const val CREATE_BUTTON = "Create"
const val CANCEL_BUTTON = "Cancel"
const val REQUEST_BUTTON = "Request"
const val ENROLL_BUTTON = "Enroll"
const val DISCARD_BUTTON = "Discard"
const val POST_BUTTON = "Post"
const val PROFILE_BUTTON = "Profile Info"
const val ROUTINE_BUTTON = "Class Routine"
const val SIGN_OUT_BUTTON = "Log Out"